### ISSUE TITLE
Question/Issue - counting same molecules

### ISSUE THREAD

**Issue by kubawlo** [ydsumith/3d-ewald-summation#1]
Hi ydsumith,

I have a doubt or perhaps misunderstanding of the double for loop for computing pairwise potentials. Let's take line 325 and on in 3d_ewald.cpp. Let's say we have 3 molecules
There you sum from molecule number 1 (i=0) to molecule 2 (i=1), because statement i<N-1 does not allow the loop to be executed for the last (i=2) molecule. Do I think right?
Moreover, to my mind, the condition for the same molecule for (i=j) will never be executed, since the other counter line 327 always starts with an index j one larger than i. 
Below I made a small snippet where the problem is illustrated. The array `molecules` will contain 'ones' in the coordinates (i,i) where the pair potential has been computed. We see no ones on the diagonal, so for example in the real space the unit vectors (nx, ny, nz) larger than one, these mirror particle interactions will not be computed. The diagonal should be zero only for the central box, i.e. (nx, ny, nz)=(0,0,0). What do you think?
I want to write an Ewald sum program in Matlab and I am trying to undestand the general flow of the program.
Keep up the good job!

`#include <iostream>
using namespace std; 
main ()
{
  cout << "Hello World";
  int N = 10;
  int molecules[N-1][N-1] = { 0 };
  for (int i = 0; i < N - 1; i++)
    {
      for (int j = i + 1; j < N; j++)
	    {
	    molecules[i][j] = 1;
	   }
    }
  return 0;
}`

**Comment by ydsumith** [comment]
Below are my comments.

> I have a doubt or perhaps misunderstanding of the double for loop for computing pairwise potentials. Let's take line 325 and on in 3d_ewald.cpp. Let's say we have 3 molecules
> There you sum from molecule number 1 (i=0) to molecule 2 (i=1), because statement i<N-1 does not allow the loop to be executed for the last (i=2) molecule. Do I think right?

     This is not correct. i is atom number, not molecule number. 

> Moreover, to my mind, the condition for the same molecule for (i=j) will never be executed, since the other counter line 327 always starts with an index j one larger than i.

     You are right. I have updated the code. Thanks!

> Below I made a small snippet where the problem is illustrated. The array `molecules` will contain 'ones' in the coordinates (i,i) where the pair potential has been computed. We see no ones on the diagonal, so for example in the real space the unit vectors (nx, ny, nz) larger than one, these mirror particle interactions will not be computed. The diagonal should be zero only for the central box, i.e. (nx, ny, nz)=(0,0,0). What do you think?

     Yes you are right for the real space contribution.

> I want to write an Ewald sum program in Matlab and I am trying to undestand the general flow of the program.
> Keep up the good job!
> 
> `#include <iostream> using namespace std; main () { cout << "Hello World"; int N = 10; int molecules[N-1][N-1] = { 0 }; for (int i = 0; i < N - 1; i++) { for (int j = i + 1; j < N; j++) { molecules[i][j] = 1; } } return 0; }`

       Below is the updated code: This may help you to understand more.
       #include <iostream>
        using namespace std; 
        main () 
        {   cout << "Hello World"; 
           int N = 10; 
           int molecules[N][N] = { 0 }; 
           for (int i = 0; i < N - 1; i++) 
           { 
               for (int j = i + 1; j < N; j++) 
               { 
                molecules[i][j] = 1; 
                }     
             } 
          return 0; 
      }
